import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dona Ziva Lanches",
  description: "Generated by create next app",
  icons: ["./ziva-logo-head.png"],
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${poppinsSans.variable} antialiased`}>
        {modal}
        {children}
      </body>
    </html>
  );
}
